spring:
  config:
    # yml 파일 분리
    import: classpath:application-oauth2secret.yml
  jpa:
    # 전송 쿼리 확인
    show-sql: true
    properties:
      hibernate:
        format_sql: true

    # 테이블 생성 후에 data.sql 실행
    defer-datasource-initialization: true

  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
  h2:
    console:
      enabled: true

jwt: # JwtProperties에서 사용
  issuer: 9uiopa@gmail.com
  secret_key: study-springboot

